#!/bin/bash

# Check if at least 3 parameters are provided
if [ $# -lt 3 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
    exit 1
fi

# Assign parameters to variables
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

# Set the default path to SSH key if not provided
if [ -z "$PATH_TO_SSH_KEY" ]; then
    PATH_TO_SSH_KEY=~/.ssh/id_rsa
fi

# Transfer the file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~
